### PR TITLE
Fix ext_domains support, refactor domain string manipulation

### PR DESCRIPTION
**Pull request by jmileham**
We discovered that using `domains` to provide xip.io support broke our ability to make requests from other machines on the same network that are also running boxen, because when put in `domains`, `*.xip.io` starts resolving to localhost, even if you type in somebody else's IP.

But when we switched it to `ext_domains`, we realized that ext_domains support is broken for the nginx proxy mode.  This patch addresses that, as well as refactoring all of the string manipulation that takes place on domains and ext_domains in the module.

Because the strings were handled differently in different places, it turns out that the /etc/resolver files could end up with spaces on the front.

For example the following:

```puppet
class {'pow':
  domains => 'pow, foo'
}
```

would result in a file named `/etc/resolver/ foo`.

This appears to have been unnoticed because the resolvers still functioned normally, even with the extra spaces.  Anyway, this PR also addresses that issue and tidies up several templates that were implementing their own string manipulation logic.

### CODE REVIEW

**Comment by jmileham** [comment]
Closing and reopening to retrigger Travis build - failed due to API rate limiter on the 1.8.7 side.

**Comment by jmileham** [comment]
Reopening.  Hopefully under the API rate limit.

**Comment by jmileham** [comment]
Guess the API rate limit is persistent.  Anyway, the tests passed on 2.0.0 once, so I'm fairly confident the tests will pass when rerun off-peak.

**Comment by jmileham** [comment]
Tests passed in Travis now that the rate limiter clock was reset.  Hopefully this PR is acceptable because it just makes a feature that was unusable before work correctly.  Thanks!

**Comment by eugeneius** [comment]
This change looks good to me - handling all whitespace manipulation in one place makes it a lot clearer.

I'm not sure who the best person from the @boxen org to review this is - @blackjid maybe?

**Comment by blackjid** [comment]
looks good to me! :+1: 
cc: @fromonesrc

**Comment by blackjid** [comment]
@fromonesrc can you please take a look at this?? thnks!

**Comment by fromonesrc** [comment]
Hi sorry I don't have involvement here anymore so I'm not the best person to review this

**Comment by blackjid** [comment]
oh, ok, sorry

**Comment by eugeneius** [comment]
Alright, let's try someone else :grin: 

@mikemcquaid, any chance you could review this change?

**Comment by mikemcquaid** [comment]
Seems fine to me. @blackjid and @eugeneius have you tested this on your local machine? Thanks!

**Comment by mikemcquaid** [comment]
(once you have: I'll merge)

**Comment by eugeneius** [comment]
I just tested it locally, and it worked as expected:

 - I pointed my `Puppetfile` at this branch and ran `boxen` - nothing changed
 - I switched back to master, added "xip.io" to `ext_domains` and ran `boxen` - the nginx config file wasn't updated to include it (reproducing the bug)
 - I switched to this branch again and ran `boxen` - the nginx config file was updated correctly

:ship:

**Comment by eugeneius** [comment]
Thanks @mikemcquaid :+1: 

And thanks @jmileham for the patch!

**Comment by jmileham** [comment]
Thanks all!

**Comment by blackjid** [comment]
Thanks! @mikemcquaid can you please make a realese with this fix? And perhaps take a look at https://github.com/boxen/puppet-pow/pull/20 and include it in the release?

Thanks!

**Comment by mikemcquaid** [comment]
@blackjid Are you interested in helping maintain this repo?

**Comment by blackjid** [comment]
ok. I can help with that.. :)

**Comment by mikemcquaid** [comment]
@blackjid Done! Have fun :wink:

**Comment by eugeneius** [comment]
@blackjid I guess I can ask you now: can you please make a release with this fix? :)

**Comment by blackjid** [comment]
@eugeneius here is the release! https://github.com/boxen/puppet-pow/releases/tag/2.3.1

**Comment by eugeneius** [comment]
Thanks! :+1:

**Pull request merged**
